# Generated by Django 4.2.13 on 2024-06-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PL', 'Planning'), ('OG', 'Ongoing'), ('CP', 'Completed'), ('CN', 'Cancelled')], default='PL', max_length=2),
        ),
    ]
