# Generated by Django 4.2.13 on 2024-06-22 10:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_address_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
