# Generated by Django 4.2.13 on 2024-07-02 18:26

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_description_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
