databases:
  - name: eventfinder
    databaseName: eventfinder
    user: eventfinder

services:
  - type: web
    name: eventfinder
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn eventfinder.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventfinder
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: OPENCAGE_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false